const heroList = [
  {hero: 'Тарталья',
   link:  './images/tartaliy.jpg'},
   {hero: 'Райден',
   link:  './images/raiden.jpg'},
   {hero: 'Чжун Ли',
   link:  './images/ded.jpg'},
   {hero: 'Розария',
   link:  './images/rozaria.jpg'},
   {hero: 'Венти',
   link:  './images/venti.jpg'},
   {hero: 'Коммисато Аяка',
   link:  './images/comisato.jpg'},
   {hero: 'Беннет',
   link:  './images/benet.jpg'},
   {hero: 'Янь Фей',
   link:  './images/yanfan.jpg'},
   {hero: 'Дилюк',
   link:  './images/dilyk.jpg'},
   {hero: 'Кадзуха',
   link:  './images/kadz.jpg'},
];